# Form implementation generated from reading ui file 'data\UI\blurDialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BlurDialog(object):
    def setupUi(self, BlurDialog):
        BlurDialog.setObjectName("BlurDialog")
        BlurDialog.resize(374, 98)
        self.gridLayout_3 = QtWidgets.QGridLayout(BlurDialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(parent=BlurDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.slider = QtWidgets.QSlider(parent=BlurDialog)
        self.slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider.setObjectName("slider")
        self.gridLayout_3.addWidget(self.slider, 1, 0, 1, 1)
        self.btn = QtWidgets.QPushButton(parent=BlurDialog)
        self.btn.setObjectName("btn")
        self.gridLayout_3.addWidget(self.btn, 2, 0, 1, 1)

        self.retranslateUi(BlurDialog)
        QtCore.QMetaObject.connectSlotsByName(BlurDialog)

    def retranslateUi(self, BlurDialog):
        _translate = QtCore.QCoreApplication.translate
        BlurDialog.setWindowTitle(_translate("BlurDialog", "BlurDialog"))
        self.label.setText(_translate("BlurDialog", "Blur"))
        self.btn.setText(_translate("BlurDialog", "OK"))
