# Form implementation generated from reading ui file 'data/MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image_lbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.image_lbl.setGeometry(QtCore.QRect(30, 30, 271, 421))
        self.image_lbl.setText("")
        self.image_lbl.setObjectName("image_lbl")
        self.save_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.save_btn.setGeometry(QtCore.QRect(690, 550, 88, 24))
        self.save_btn.setObjectName("save_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Editor"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
